services:
  redis:
    container_name: spotify-composer-redis
    image: redis
    command: redis-server
    ports:
    - 6379:6379

  database:
    container_name: spotify-composer-database
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    ports:
    - ${DB_PORT}:5432